clean: true
author: Shiguredo Inc. and Masashi Ono (akisute)
author_url: https://sora.shiguredo.jp/
github_url: https://github.com/shiguredo/sora-ios-sdk/
github_file_prefix: https://github.com/shiguredo/sora-ios-sdk/blob/master
root_url: https://sora-ios-sdk.shiguredo.jp/
theme: apple
min_acl: public
sdk: iphoneos
module: Sora
module_version: 2025.2.0
swift_build_tool: "xcodebuild"
xcodebuild_arguments:
    - -parallelizeTargets
    - -scheme
    - Sora
    - -destination
    - 'generic/platform=iOS'

