clean: true
author: Shiguredo Inc. and Masashi Ono (akisute)
author_url: https://sora.shiguredo.jp/
github_url: https://github.com/shiguredo/sora-ios-sdk/
github_file_prefix: https://github.com/shiguredo/sora-ios-sdk/blob/master
root_url: https://sora-ios-sdk.shiguredo.jp/
theme: apple
min_acl: public
sdk: iphoneos
module: Sora
module_version: 2023.2.0
swift_version: 5.8.1
xcodebuild_arguments:
    - -parallelizeTargets
    - -sdk
    - iphoneos16.4
    - -workspace
    - Sora.xcworkspace
    - -scheme
    - Sora
