included:
  - Sora
excluded:
  - Pods
disabled_rules:
  - identifier_name
  - force_cast
  - force_try
  - cyclomatic_complexity
  - function_body_length
  - file_length
  - line_length
  - type_body_length
  - weak_delegate
  - opening_brace
  - closing_brace
  - anonymous_argument_in_multiline_closure
  - conditional_returns_on_newline
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - colon
  - comma
  - comment_spacing
  - trailing_comma
  - trailing_newline
  - trailing_whitespace
  - closure_parameter_position
  - closure_end_indentation
  - closure_spacing
  - for_where
  - large_tuple
  - todo